# Define the number of machines that we support
NUM_MACHINES = 8
CORES_PER_MACHINE = 18
TOTAL_CPUS = NUM_MACHINES * CORES_PER_MACHINE
SIM_TIME = 10000
TASK_ARRIVAL_RATE = 0.5  
MEAN_TASK_DURATION = 20
CHECKPOINT_OVERHEAD = 2
MIGRATION_COST = 3  
SEED = 42